### ISSUE TITLE
NullPointerException:  "AhoyOnboarderAdapter.getCount()' 

### ISSUE THREAD

**Issue by AlaaZarifa** [codemybrainsout/ahoy-onboarding#15]
I just used the same [class ](https://github.com/codemybrainsout/ahoy-onboarding/blob/master/app/src/main/java/com/codemybrainsout/onboarding/GradientBackgroundExampleActivity.java)in the sample project and once I run, it shows the first page as blank (no photo or texts) and a next button, if I clicked it it crashes and give me this error : 
 
```
 
  FATAL EXCEPTION: main
    Process: com.alaasamizarifa.quotex, PID: 10372
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.codemybrainsout.onboarder.AhoyOnboarderAdapter.getCount()' on a null object reference
       at com.codemybrainsout.onboarder.AhoyOnboarderActivity.onClick(AhoyOnboarderActivity.java:105)
       at android.view.View.performClick(View.java:5226)
       at android.view.View$PerformClick.run(View.java:21266)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:168)
       at android.app.ActivityThread.main(ActivityThread.java:5845)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
```

**Comment by AlaaZarifa** [comment]
nevermind, I was using the wrong `onCreate` method, I was passing this `@Nullable PersistableBundle persistentState` as a second parameter, I don't how it got there to be honest 😕  once I removed it, it worked normally 😄

anyhow, thanks for the awesome library 👍
